steps:

  - label: ":hammer: Example Script"
    command: "scripts/script.sh"
    artifact_paths: "artifacts/*"

  - command: "echo succesful command"
    label: ":white_check_mark: Example command after wait instruction"

  - label: ":hammer: Script with metadata variables"
    command: "scripts/staging.sh"

  - wait 

  - trigger: buildkite-cd
