steps:

  - label: ":hammer: Example Script"
    command: "scripts/script.sh"
    artifact_paths: "artifacts/*"

  - command: "echo succesful FEATURE CI command"
    label: ":white_check_mark: Example FEATURE CI command after wait instruction"

  - wait 

  - trigger: buildkite-cd
